apiVersion: v1
kind: Pod
metadata:
  name: config-test-pod
  labels:
    role: config-test-pod
spec:
  containers:
    - name: config-demo
      image: busybox
      command: ["sh", "-c", "echo CONFIG_MSG=$CONFIG_MSG && echo CONFIG_SECRET=$CONFIG_SECRET && sleep 3600"]
      imagePullPolicy: IfNotPresent
      env:
        - name: CONFIG_MSG
          valueFrom:
            configMapKeyRef:
              key: CONFIG_MSG
              name: demo-config
        - name: CONFIG_SECRET
          valueFrom:
            secretKeyRef:
              key: CONFIG_SECRET
              name: demo-secret
#      ports:
#        - name: config-test-pod
#          containerPort: 80
#          protocol: TCP
#  restartPolicy: Always
  