# pod-file-demo.yaml
# 목적: cm-file-demo ConfigMap을 /etc/config 디렉토리에 파일 형태로 마운트
apiVersion: v1
kind: Pod
metadata:
  name: pod-file-demo       # Pod 이름 (file 방식임을 알 수 있게)
spec:
  containers:
    - name: demo-container
      image: busybox          # 가벼운 테스트용 이미지
      command: [ "sh", "-c", "sleep 3600" ]   # Pod 유지 (1시간 대기)
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config    # ConfigMap을 이 디렉토리에 파일로 마운트
          readOnly: true            # 읽기 전용으로 설정
  volumes:
    - name: config-volume
      configMap:
        name: cm-file-demo        # 위 ConfigMap 이름 참조

  # kv format
#  key: "value"
#  $actual-config-file$: "name.properties"

  # file format
#  name.properties: |
#    field=value1,value2
