# 여러 DockerFile을 하나로 관리하기 위함
# 하나의 컨테이너를 Services라고 부른다.
services:
  my-web-server:
    container_name: web-server
    image: nginx
    ports:
      - "80:80"

# Redis
  my-cache-server:
    image: redis
    ports:
      - "6379:6379"

# docker Mysql
  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"