name: deploy.yml
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug SSH
        run: |
          ssh -vvv user@host
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          use_insecure_cipher: true
          host_key_verification: false
          script: |
            cd ~/projects/DevOps-practice-lab &&
            git pull &&
            ./deploy.sh
